### ISSUE TITLE
-p Argument returns error.

### ISSUE THREAD

**Issue by zdog16** [zdog16/pass-inator#2]
When running the exmaple.py with the -p (passprase) argument, I get the following error.

```
C:\Users\{username}\Python\Development\pass-inator>example.py -p
Traceback (most recent call last):
  File "C:\Users\{username}\Python\Development\pass-inator\example.py", line 38, in <module>
    password = generator.generate_passphrase(simpleOutput=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\{username}\Python\Development\pass-inator\passInator.py", line 227, in generate_passphrase
    for i in range(0, secrets.choice(range(self.number_of_words[0], self.number_of_words[1]))):
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\{username}\AppData\Local\Programs\Python\Python311\Lib\random.py", line 373, in choice
    raise IndexError('Cannot choose from an empty sequence')
IndexError: Cannot choose from an empty sequence
```

**Comment by zdog16** [comment]
Solved in latest push. The secrets module did not like being handed a range of [2, 2]. Added a check for ranges.
